server:
  port : 8081

db:
  entity:
    package: com.company.schedule.management.system.model

datasource:
  username: postgres
  password: postgres
  url: jdbc:postgresql://0.0.0.0:5532/postgres
  driver-class-name: org.postgresql.Driver

