  spring:
    datasource:
      username: postgres
      password: postgres
      url: jdbc:postgresql://localhost:5532/postgres
      driver-class-name: org.postgresql.Driver

    flyway:
      baseline-on-migrate: true


