server:
  port: 8081

spring:
  datasource:
    username: "postgres"
    password: "postgres"
    url: "jdbc:postgresql://0.0.0.0:5832/postgres"
    driver-class-name: "org.postgresql.Driver"
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.company.schedule.management.system: DEBUG
    com.company.schedule.management.system.repository: DEBUG
    com.company.schedule.management.system.service: DEBUG
    org.hibernate: ERROR

