version: "3.3"
services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5832:5432"